// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebOlympiada.Models;

public partial class aspnetOGContext : DbContext
{
    public aspnetOGContext(DbContextOptions<aspnetOGContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Sport> Sports { get; set; }

    public virtual DbSet<Sportovec> Sportovecs { get; set; }

    public virtual DbSet<Type> Types { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Sport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sports__3213E83F603D15AB");

            entity.HasIndex(e => e.TypeId, "IX_Sports_TypeID");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");

            entity.HasOne(d => d.Type).WithMany(p => p.Sports)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Sports.Types");
        });

        modelBuilder.Entity<Sportovec>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sportove__3214EC07DAF26366");

            entity.ToTable("Sportovec");

            entity.Property(e => e.Jmeno)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Narodnost)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Prijmeni)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<Type>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Types__3214EC07AA286D7B");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}