// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebOlympiada.Models;

public partial class aspnetOGContext : DbContext
{
    public aspnetOGContext(DbContextOptions<aspnetOGContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Rozhodci> Rozhodcis { get; set; }
    public virtual DbSet<Divaci> Divacis { get; set; }

    public virtual DbSet<Sport> Sports { get; set; }

    public virtual DbSet<Type> Types { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Rozhodci>(entity =>
        {
            entity.ToTable("Rozhodci");

            entity.Property(e => e.Jmeno).IsRequired();
            entity.Property(e => e.Prijmeni).IsRequired();
        modelBuilder.Entity<Divaci>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Divaci__3214EC072BFDF6C1");

            entity.ToTable("Divaci");

            entity.Property(e => e.Jmeno).HasMaxLength(50);
            entity.Property(e => e.Prijmeni).HasMaxLength(50);
        });

        modelBuilder.Entity<Sport>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Sports__3213E83F603D15AB");

            entity.HasIndex(e => e.TypeId, "IX_Sports_TypeID");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasColumnName("name");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");

            entity.HasOne(d => d.Type).WithMany(p => p.Sports)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("Sports.Types");
        });

        modelBuilder.Entity<Type>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Types__3214EC07AA286D7B");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}