// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebOlympiada.Models;

public partial class Sport
{
    public string Name { get; set; }

    public int TypeId { get; set; }

    public int Id { get; set; }

    public virtual Type Type { get; set; }
}