// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebOlympiada.Models;

public partial class Sportovec
{
    public int Id { get; set; }

    public string Jmeno { get; set; }

    public string Prijmeni { get; set; }

    public string Narodnost { get; set; }
}